"""Module for defining user-level constants."""

IDENTIFIER = "users"
BASE_URL = f"/{IDENTIFIER}"
MSG_LOGOUT_SUCCESS = "Logged out successfully."
EXC_MSG_USER_WITH_ID_EXISTS = "User with id already exists."
EXC_MSG_USER_NOT_FOUND = "User with id not found."
EXC_MSG_WRONG_PASSWORD = "Incorrect password provided for user id."
EXC_MSG_LOGIN_FAILED = "Login failed. Please check your credentials."
EXC_MSG_ACCESS_TOKEN_NOT_FOUND = "Access token not found."
EXC_MSG_ACCESS_TOKEN_INVALID = "Access token invalid."
EXC_MSG_REFRESH_TOKEN_NOT_FOUND = "Refresh token not found."
EXC_MSG_REFRESH_TOKEN_INVALID = "Refresh token invalid."
EXC_MSG_TOKEN_EXPIRED = "Token expired."
EXC_MSG_MISSING_PERMISSION = "Missing required permission."
