"""Add fingerprint fields to registered browsers

Revision ID: 115c1d632cbe
Revises: 0ecdf8d236f3
Create Date: 2026-01-10 23:02:54.218428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '115c1d632cbe'
down_revision: Union[str, None] = '0ecdf8d236f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_browsers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('fingerprint_hash', sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('user_agent', sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('ip_address', sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                'registered_at',
                sa.DateTime(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'last_seen',
                sa.DateTime(),
                server_default=sa.text('(CURRENT_TIMESTAMP)'),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                'is_active',
                sa.Boolean(),
                nullable=False,
                server_default='1',
            )
        )
        batch_op.create_unique_constraint(
            'uq_registered_browsers_browser_name', ['browser_name']
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_browsers', schema=None) as batch_op:
        batch_op.drop_constraint(
            'uq_registered_browsers_browser_name', type_='unique'
        )
        batch_op.drop_column('is_active')
        batch_op.drop_column('last_seen')
        batch_op.drop_column('registered_at')
        batch_op.drop_column('ip_address')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('fingerprint_hash')

    # ### end Alembic commands ###
