"""Add RegisteredBrowser model and external_clock_allowed to Employee

Revision ID: 6f5391cead75
Revises: 368a2b616435
Create Date: 2026-01-04 19:52:56.081834

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6f5391cead75"
down_revision: Union[str, None] = "368a2b616435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registered_browsers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("browser_uuid", sa.String(), nullable=False),
        sa.Column("browser_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("browser_uuid"),
    )
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "external_clock_allowed",
                sa.Boolean(),
                nullable=False,
                server_default="0",
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("employees", schema=None) as batch_op:
        batch_op.drop_column("external_clock_allowed")

    op.drop_table("registered_browsers")
    # ### end Alembic commands ###
