"""Add active session tracking to registered browsers

Revision ID: a1b2c3d4e5f6
Revises: 115c1d632cbe
Create Date: 2026-01-11 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '115c1d632cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_browsers', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('active_session_fingerprint', sa.String(), nullable=True)
        )
        batch_op.add_column(
            sa.Column('active_session_started', sa.DateTime(), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registered_browsers', schema=None) as batch_op:
        batch_op.drop_column('active_session_started')
        batch_op.drop_column('active_session_fingerprint')

    # ### end Alembic commands ###
